//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quotation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ID = Guid.NewGuid().ToString();
            this.Sjbj = 0;
            this.q1765_jsf = new HashSet<q1765_jsf>();
            this.q1765_jszlf = new HashSet<q1765_jszlf>();
            this.q1765_psf = new HashSet<q1765_psf>();
            this.q1765_rdf = new HashSet<q1765_rdf>();
            this.q1765_wgcpj = new HashSet<q1765_wgcpj>();
            this.q1765_yfcl = new HashSet<q1765_yfcl>();
            this.q1765_zb = new HashSet<q1765_zb>();
        }
    
        public string ID { get; set; }
        public Nullable<int> Sjbj { get; set; }
        public Nullable<System.DateTime> Szsj { get; set; }
        public string XMMC { get; set; }
        public string Mb { get; set; }
        public string Lj { get; set; }
        public string Bzdw { get; set; }
        public Nullable<int> Bznf { get; set; }
        public string Bz { get; set; }
        public string Dwdh { get; set; }
        public string Dwqc { get; set; }
        public string Szssdq { get; set; }
        public string Pzjdbs { get; set; }
        public string Ssjdbj { get; set; }
        public string Sshylb { get; set; }
    
        public virtual ICollection<q1765_jsf> q1765_jsf { get; set; }
        public virtual ICollection<q1765_jszlf> q1765_jszlf { get; set; }
        public virtual ICollection<q1765_psf> q1765_psf { get; set; }
        public virtual ICollection<q1765_rdf> q1765_rdf { get; set; }
        public virtual ICollection<q1765_wgcpj> q1765_wgcpj { get; set; }
        public virtual ICollection<q1765_yfcl> q1765_yfcl { get; set; }
        public virtual ICollection<q1765_zb> q1765_zb { get; set; }
    }
}
