//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quotation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class q1765_rdf
    {
        public q1765_rdf()
        {
            this.ID = Guid.NewGuid().ToString();
            this.Sjbj = 0;
            this.Sfsd = false;
        }
    
        public string ID { get; set; }
        public Nullable<int> Sjbj { get; set; }
        public Nullable<System.DateTime> Szsj { get; set; }
        public Nullable<bool> Sfsd { get; set; }
        public Nullable<int> Ztbj { get; set; }
        public string ProjectID { get; set; }
        public string PID { get; set; }
        public string Xh { get; set; }
        public string Mc { get; set; }
        public string Fylx { get; set; }
        public string Jldw { get; set; }
        public Nullable<decimal> Hj { get; set; }
        public Nullable<decimal> Yl { get; set; }
        public Nullable<decimal> Dj { get; set; }
        public Nullable<decimal> Je { get; set; }
        public Nullable<decimal> Qtfy { get; set; }
        public string Bz { get; set; }
        public string Kz1 { get; set; }
        public string Kz2 { get; set; }
        public string Kz3 { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
