//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quotation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class q1765_zb
    {
        public q1765_zb()
        {
            this.ID = Guid.NewGuid().ToString();
            this.Sjbj = 0;
            this.Czsj = DateTime.Now;
            this.Sfsd = false;
        }
    
        public string ID { get; set; }
        public Nullable<int> Sjbj { get; set; }
        public Nullable<System.DateTime> Czsj { get; set; }
        public Nullable<bool> Sfsd { get; set; }
        public Nullable<int> Ztbj { get; set; }
        public string ProjectID { get; set; }
        public string PID { get; set; }
        public string Xh { get; set; }
        public string Mc { get; set; }
        public Nullable<int> Sjlx { get; set; }
        public Nullable<decimal> Mbjf { get; set; }
        public Nullable<decimal> Gshj { get; set; }
        public Nullable<decimal> SjfJe { get; set; }
        public Nullable<decimal> ClfJe { get; set; }
        public Nullable<decimal> ClfQzbjt { get; set; }
        public Nullable<decimal> ClfQzrdf { get; set; }
        public Nullable<decimal> WxfJe { get; set; }
        public Nullable<decimal> WxfQzbjt { get; set; }
        public Nullable<decimal> ZyfJe { get; set; }
        public Nullable<decimal> ZyfQzbjt { get; set; }
        public Nullable<decimal> SyfJe { get; set; }
        public Nullable<decimal> GzfJe { get; set; }
        public Nullable<decimal> GzJe { get; set; }
        public Nullable<decimal> GlfBl { get; set; }
        public Nullable<decimal> GlfJe { get; set; }
        public Nullable<decimal> XjJe { get; set; }
        public Nullable<decimal> SyBl { get; set; }
        public Nullable<decimal> SyJe { get; set; }
        public Nullable<decimal> BkyjfBl { get; set; }
        public Nullable<decimal> BkyjfJe { get; set; }
        public Nullable<decimal> Qtfy { get; set; }
        public string Rwlx { get; set; }
        public string Cydw { get; set; }
        public string Bbdw { get; set; }
        public Nullable<decimal> Ptsl { get; set; }
        public string Sm { get; set; }
        public string Rwbm { get; set; }
        public string Kz1 { get; set; }
        public string Kz2 { get; set; }
        public string Kz3 { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
