//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quotation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class q1765_psf
    {
        public q1765_psf()
        {
            this.ID = Guid.NewGuid().ToString();
            this.Sjbj = 0;
            this.Sfsd = false;
        }
    
        public string ID { get; set; }
        public Nullable<int> Sjbj { get; set; }
        public Nullable<System.DateTime> Szsj { get; set; }
        public Nullable<bool> Sfsd { get; set; }
        public Nullable<int> Ztbj { get; set; }
        public string ProjectID { get; set; }
        public string PID { get; set; }
        public string Xh { get; set; }
        public string Mc { get; set; }
        public Nullable<decimal> Hj { get; set; }
        public Nullable<decimal> Cs { get; set; }
        public Nullable<decimal> Ts { get; set; }
        public Nullable<decimal> HyfRs { get; set; }
        public Nullable<decimal> HyfBz { get; set; }
        public Nullable<decimal> HyfXj { get; set; }
        public Nullable<decimal> ClfRs { get; set; }
        public Nullable<decimal> ClfSsbz { get; set; }
        public Nullable<decimal> ClfSsf { get; set; }
        public Nullable<decimal> ClfJtfbz { get; set; }
        public Nullable<decimal> ClfJtf { get; set; }
        public Nullable<decimal> ClfXj { get; set; }
        public Nullable<decimal> ZjzxfRs { get; set; }
        public Nullable<decimal> ZjzxfBz { get; set; }
        public Nullable<decimal> ZjzxfXj { get; set; }
        public Nullable<decimal> Qtfy { get; set; }
        public string Fl { get; set; }
        public string Bz { get; set; }
        public string Kz1 { get; set; }
        public string Kz2 { get; set; }
        public string Kz3 { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
